FEAT Rename a board
awi2017-option1group3/Prello-Client pull request #42
Opened 2017-10-31 09:43 UTC by KenAlin

Allows you to rename a board, by clicking on its title.

:information_source: Some changes where made to EditField.
* dragHandleProps : Is now not required
* EditField will now update state when props change. It is mandatory here, because we receive the board's title after EditField is rendered once.
* These changes doesn't break others EditField (for cards and lists titles)

2017-10-31 11:04 UTC, Tombean requested changes

2017-10-31 11:04 UTC, Tombean commented on src/commons/editField/EditField.jsx
> +  dragHandleProps: PropTypes.object,
Remove it

2017-10-31 18:02 UTC, TheoGauchoux submitted a review, later dismissed

2017-10-31 18:02 UTC, TheoGauchoux commented on src/containers/board/reducer.js
> +  data: [],
Why did you replace the `title` property by an array called `data` ?

2017-10-31 18:02 UTC, TheoGauchoux commented on src/commons/editField/EditField.jsx
> +  dragHandleProps: PropTypes.object,
No, I think we need it for card to just grab the title to drag and drop the card.

2017-11-01 07:44 UTC, KenAlin commented on src/containers/board/reducer.js
> +  data: [],
To be more consistent with others reducers

2017-11-02 08:00 UTC, KenAlin commented on src/commons/editField/EditField.jsx
> +  dragHandleProps: PropTypes.object,
`.isRequired` is already removed

2017-11-02 18:51 UTC, KenAlin commented on src/containers/board/reducer.js
> +  data: [],
Request for comment : data may be needed in a near future, to handle more properties than just "title". So, do I have to keep "title" or should I change to "data" ?

2017-11-06 09:22 UTC, TheoGauchoux commented on src/containers/board/reducer.js
> +  data: [],
The field `data` is used for collection reducers (like boardS, listS, cardS), not for board or card. `Data` is usually an array of element (of cards, board, lists, etc).

2017-11-07 15:03 UTC, Tombean approved these changes

2017-11-07 15:03 UTC, merged